import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#1A3636',
  },
  nav: {
    marginTop: 130,
    flexDirection: 'row',
    gap: 80,
  },
  clock: {
    marginTop: 120,
    justifyContent: 'center',
    alignItems: 'center',
    width: 300,
    height: 300,
    padding: 20,
    backgroundColor: '#1A3636',
    borderRadius: 150,
    borderWidth: 4,
    borderColor: '#677D6A'
  },
  timeText: {
    fontSize: 46,
    fontWeight: 'bold',
    color: '#677D6A',
  },
  textClock: {
    color: '#D6BD98',
    bottom: 15,
    fontWeight: '500',
  },
  textClockHeart: {
    fontSize: 16,
    bottom: 10,
  },
  status: {
    color: '#D6BD98',
    top: 15,
    fontWeight: '500',
  },
  buttons: {
    position: 'absolute',
    flexDirection: 'row',
    gap: 120,
    bottom: 100,
  },
  play: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    backgroundColor: '#D6BD98',
    padding: 20,
    borderRadius: 50,
  },
  playText: {
    color: '#677D6A',
    fontSize: 24,
    fontWeight: '500',
    textTransform: "uppercase",
  },
  treino: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    backgroundColor: '#D6BD98',
    padding: 20,
    borderRadius: 50,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0)',
  },
  modalContent: {
    backgroundColor: '#3d3d3d',
    padding: 20,
    alignItems: 'center',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  colors: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  colorOption: {
    width: '40%',
    height: 50,
    borderRadius: 25,
    margin: 10,
    marginHorizontal: 18,
    marginBottom: 30,
    borderWidth: 2,
    borderColor: '#D6BD98',
  },
  closeButton: {
    marginTop: 20,
    marginBottom: 20,
    fontSize: 20,
    color: '#D6BD98',
    fontWeight: '400',
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  sounds: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 20,
    marginBottom: 50,
    marginTop: 10,
    justifyContent: 'center',
  },
  soundOption: {
    width: 150,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#677D6A',
    borderRadius: 10,
    marginVertical: 5,
  },
  settingContainer: {
    marginVertical: 10,
    width: '100%',
    alignItems: 'center',
  },
  settingLabel: {
    fontSize: 16,
    marginBottom: 5,
  },
  textInput: {
    width: '80%',
    height: 40,
    borderColor: '#ddd',
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    fontSize: 16,
    marginBottom: 50,
  },
  slider: {
    width: 300,
    height: 30,
    marginVertical: 10,
  },
  time: {
    fontSize: 16,
    marginTop: 20,
    color: '#D6BD98',
    fontWeight: '400',
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  break: {
    fontSize: 16,
    marginTop: 30,
    color: '#D6BD98',
    fontWeight: '400',
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  end: {
    marginBottom: 30,
  },
});

export default styles;
